services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  user-service:
    build: ./user_service
    container_name: user-service

    ports:
      - "8000:8000"

  music-service:
    build: ./music_service
    container_name: music-service

    ports:
      - "8001:8001"

  history-service:
    build: ./history_service
    container_name: history-service

    ports:
      - "8002:8002"

    depends_on:
      - kafka

  recommendation-service:
    build: ./recommendation_service
    container_name: recommendation-service

    ports:
      - "8003:8003"

    depends_on:
      - kafka
      - user-service
      - music-service